import { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import ClassCard from '../components/Classes/ClassCard'
import ClassroomHeader from '../components/Classroom/ClassroomHeader'

const ArchivedClasses: NextPage = () => {
    return (
        <div>

            <Head>
                <title>Classroom</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div>
                <ClassroomHeader />

                <div className='p-5'>

                    <div className='mt-5'>

                        <div className="grid grid-flow-row auto-rows-max  grid-cols-1 sm:grid-cols-2 md:grid-cols-3 xl:grid-cols-4 gap-4">
                            <ClassCard />
                            <ClassCard />
                            <ClassCard />
                            <ClassCard />

                        </div>


                    </div>

                </div>


            </div>

        </div>
    )
}

export default ArchivedClasses;