import Head from 'next/head'
import React from 'react'
import CalendarBody from '../components/Calendar/CalendarBody'
import ClassroomHeader from '../components/Classroom/ClassroomHeader'

const Calendar = () => {
    return (
        <div>

            <Head>
                <title>Classroom</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div>
                <ClassroomHeader />
                <div className='p-5 h-[85vh] '>
                    <CalendarBody />

                </div>
            </div>

        </div>
    )
}

export default Calendar