import { NextPage } from 'next'
import Head from 'next/head'
import React, { useEffect } from 'react'
import ClassCard from '../components/Classes/ClassCard'
import ClassesBody from '../components/Classes/ClassesBody'
import ClassesHeader from '../components/Classes/ClassesHeader'
import ClassroomHeader from '../components/Classroom/ClassroomHeader'
import LoadingScreen from '../components/Global/LoadingScreen'
import { useAuth } from '../context/AuthUserContext'
import { useRouter } from 'next/router'

const Classes: NextPage = () => {

    const { authUser, loading } = useAuth();
    const router = useRouter();

    useEffect(() => {

        if(!authUser){
            router.replace('/');
        }

    }, [authUser]);

    if (loading && !authUser) {
        return <LoadingScreen />
    }else if(!loading && authUser) {
        return (
            <div>

                <Head>
                    <title>Classroom</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <div>
                    <ClassroomHeader />

                    <div className='p-5'>
                        <ClassesHeader />
                        <ClassesBody />
                    </div>

                </div>

            </div>
        )
    }else{
        return <LoadingScreen />
    }


}

export default Classes