import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Button, ButtonGroup } from '@chakra-ui/react'

const Home: NextPage = () => {
  return (
    <div>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1 className="text-3xl font-bold underline">
          Hello world!
        </h1>

      </div>

    </div>
  )
}

export default Home
