import Head from 'next/head'
import React from 'react'
import ClassroomHeader from '../components/Classroom/ClassroomHeader'
import ViewAssignmentBody from '../components/Classroom/ViewAssignment/ViewAssignmentBody'

const ViewAssignment = () => {
    return (
        <div>
            <Head>
                <title>Assignment</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div>
                <ClassroomHeader />
                <ViewAssignmentBody />
            </div>
        </div>

    )
}

export default ViewAssignment